version: '2.25.5'
services:
    portainer-ce:
        image: 'portainer/portainer-ce:latest'
        volumes:
            - 'cupboard_data:/data'
            - '/var/run/docker.sock:/var/run/docker.sock'
        restart: always
        container_name: portainer
        ports:
            - '9443:9443'
            - '8000:8000'

    home-assistant:
        image: homeassistant/home-assistant
        ports:
            - '8123:8123'
        restart: always
        volumes:
            - '~/homeassistant/config:/config'
        container_name: homeassistant

    qbittorrent:
        image: 'lscr.io/linuxserver/qbittorrent:latest'
        restart: always
        volumes:
            - '/home/luser/downloads:/downloads'
            - '/home/luser/qbittorrent/config:/config'
        ports:
            - '6881:6881/udp'
            - '6881:6881'
            - '8080:8080'
        environment:
            - WEBUI_PORT=8080
            - TZ=Etc/UTC
            - PGID=1000
            - PUID=1000
        container_name: qbittorrent

    heimdall:
        image: 'lscr.io/linuxserver/heimdall:latest'
        restart: always
        volumes:
            - '/home/luser/heimdall/config:/config'
        ports:
            - '4443:443'
            - '7888:80'
        environment:
            - TZ=America/Los_Angeles
            - PGID=1000
            - PUID=1000
        container_name: heimdall

    plex:
        image: linuxserver/plex
        restart: always
        volumes:
            - '/media/NFS:/data'
            - '~/plex/transcode:/transcode'
            - '~/plex/database:/config'
        environment:
            - TZ=America/Los_Angeles
            - PLEX_CLAIM=claim-jLVoNaLHZashPJKJR7yZ
        ports:
            - '32400:32400'
        container_name: plex

    it-tools:
        image: 'corentinth/it-tools:latest'
        ports:
            - '8081:80'
        restart: always
        container_name: 'it-tools'

    watchtower:
        image: 'v2tec/watchtower'
        restart: always
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        container_name: watchtower
    wordpress:
        image: 'wordpress'
        restart: always
        environment:
          - WORDPRESS_DB_HOST=mariadb
          - WORDPRESS_DB_USER='root'
          - WORDPRESS_DB_PASSWORD='85awrHF8rthsrthsths'
          - WORDPRESS_DB_NAME='wordpress'
        ports:
          - 10100:80
        volumes:
          - '/home/luser/wordpress/html:/var/www/html'
        container_name: 'wordpress'
    mariadb:
        image: 'mariadb'
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD='85awrHF8rthsrthsths'
          - MYSQL_DATABASE='wordpress'
        volumes:
          - '/home/luser/wordpress/db:/var/lib/mysqlx'
        container_name: wordpress_mariadb
volumes:
  cupboard_data: